### ISSUE TITLE
Is Clang required for source wheels?

### ISSUE THREAD

**Issue by HajoRed** [astral-sh/python-build-standalone#230]
Hey there,

I am currently trying to get an installation to work on Linux (specifically Ubuntu 20.04+) which is working so far.
When trying to install some packages with pip which are only deployed as source code, installation fails with a `clang not found` message.
Is Clang strictly needed for this scenario or can source packages be build with gcc as well?
If they can be build with gcc, how can this be done?

Best regards

**Comment by bluss** [comment]
In many cases they can be built by just setting the environment variable, CC=gcc or CC=gcc-XY where XY is the version. In some cases however,  there are harder issues which are not so easy to solve, see this chapter: https://gregoryszorc.com/docs/python-build-standalone/main/quirks.html#references-to-build-time-paths

**Comment by charliermarsh** [comment]
Yeah the distributions use clang by default, but you can override them as described above.
