### ISSUE TITLE
unable to install poetry

### ISSUE THREAD

**Issue by mustafa0x** [astral-sh/python-build-standalone#262]
ref: https://github.com/jdx/mise/issues/1743

```
poetry/1.8.2/venv/bin/python3:
  error while loading shared libraries:
  poetry/1.8.2/venv/bin/../lib/libpython3.10.so.1.0:
  cannot open shared object file:
  No such file or directory
```

**Comment by egnor** [comment]
I believe this is specific to the `linux-musl` flavor (not a problem in the `linux-gnu` flavor), and _probably_ an issue with poetry on non-dynamically-linked Python but I haven't dug into it.

**Comment by charliermarsh** [comment]
Yeah this is specific to the statically-linked Pythons. I suspect you want the dynamically-linked Pythons, and the statically-linked Pythons are being installed in error?
