### ISSUE TITLE
Broken documentation link in release note 20240726

### ISSUE THREAD

**Issue by bluss** [astral-sh/python-build-standalone#295]
In this release https://github.com/indygreg/python-build-standalone/releases/tag/20240726
it's using a link that doesn't go anywhere:
https://gregoryszorc.com/docs/python-build-standalone/20240726/running.html

Good link is presumably https://gregoryszorc.com/docs/python-build-standalone/20240725/running.html

**Comment by charliermarsh** [comment]
That's strange... Did the docs not update on that release?

**Comment by bluss** [comment]
Well, the link works now when it didn't before. Did you fix it? :)

**Comment by charliermarsh** [comment]
I updated it to the previous release. I’m planning to release today anyway so will check then.

**Comment by charliermarsh** [comment]
Okay also failed in the last. Will look into it.

**Comment by indygreg** [comment]
The docs on gregoryszorc.com key off commits to the `main` branch to trigger generation. Since the new release process doesn't create any commits to `main`, it doesn't see the need to create docs when a tag is created. I can fix this easily enough...
