### ISSUE TITLE
Object files missing?

### ISSUE THREAD

**Issue by vadimcn** [astral-sh/python-build-standalone#378]
Linking libpython 3.13 from object files in `cpython-3.13.0+20241016-x86_64_v2-unknown-linux-gnu-pgo-full.tar.zst` fails because of undefined `_PyToken_Init`, `_PyTokenizer_FromFile`, `_PyTokenizer_Get`, etc symbols.

Upon closer inspection, it looks like object files related to [`Parser/lexer`](https://github.com/python/cpython/tree/main/Parser/lexer) and [`Parser/tokenizer`](https://github.com/python/cpython/tree/main/Parser/tokenizer) are missing from `python/build/Parser`?

**Comment by indygreg** [comment]
Seems like a valid issue.

Ideally the fix to this involves extending the Rust validation code to ensure all symbols from libpython can be found in shipped object files.
