### ISSUE TITLE
cpython-3.8.6 doesn't really support 3.8.6? 

### ISSUE THREAD

**Issue by peterboston** [astral-sh/python-build-standalone#62]
First, I want to say I really appreciate your work here. I am a first time user. I don't know what I found is an issue or not. I downloaded the cpython-3.8.6-x86_64-unknown-linux-gnu-debug-20201020T0627.tar.zst. I found when I execute the "python3 --version", it says "Python 3.6.8". When I execute the "python3.8 --version", it says to me "bash: python3.8: command not found...
Install package 'python38' to provide command 'python3.8'? [N/y]"

I typed "y" and a few packages were installed on my CentOS 8. But it was installed system wide. What I expected is the installation will happen within your python/install folder and then your portable python truly support 3.8.6. 

I think I probably missed something and your cpython-3.8.6 supports 3.8.6 already. Is there any simple instruction to show how to use/config your wonderful standalone distribution?

**Comment by indygreg** [comment]
If you simply type `python` or `python3.8` in your shell, your shell will attempt to find an executable file of that name in the directories defined by the `PATH` environment variable.

From the output you pasted, it looks like your request to run various `python` executables uses a Python install on the system.

Try typing the full path to the python executable inside the extracted archive. e.g. `python/install/bin/python3.8` or `./python3.9`. This will run an explicit path and won't fall back to scanning other directories for binaries.
